MODULE MATHIO
INTERFACE EXPORT
	MODULE PROCEDURE EXPORT_ITEN1
	MODULE PROCEDURE EXPORT_STEN1
	MODULE PROCEDURE EXPORT_DTEN1
	MODULE PROCEDURE EXPORT_CTEN1
	MODULE PROCEDURE EXPORT_ZTEN1
	MODULE PROCEDURE EXPORT_ITEN2
	MODULE PROCEDURE EXPORT_STEN2
	MODULE PROCEDURE EXPORT_DTEN2
	MODULE PROCEDURE EXPORT_CTEN2
	MODULE PROCEDURE EXPORT_ZTEN2
	MODULE PROCEDURE EXPORT_ITEN3
	MODULE PROCEDURE EXPORT_STEN3
	MODULE PROCEDURE EXPORT_DTEN3
	MODULE PROCEDURE EXPORT_CTEN3
	MODULE PROCEDURE EXPORT_ZTEN3
	MODULE PROCEDURE EXPORT_ITEN4
	MODULE PROCEDURE EXPORT_STEN4
	MODULE PROCEDURE EXPORT_DTEN4
	MODULE PROCEDURE EXPORT_CTEN4
	MODULE PROCEDURE EXPORT_ZTEN4
	MODULE PROCEDURE EXPORT_ITEN5
	MODULE PROCEDURE EXPORT_STEN5
	MODULE PROCEDURE EXPORT_DTEN5
	MODULE PROCEDURE EXPORT_CTEN5
	MODULE PROCEDURE EXPORT_ZTEN5
	MODULE PROCEDURE EXPORT_ITEN6
	MODULE PROCEDURE EXPORT_STEN6
	MODULE PROCEDURE EXPORT_DTEN6
	MODULE PROCEDURE EXPORT_CTEN6
	MODULE PROCEDURE EXPORT_ZTEN6
	MODULE PROCEDURE EXPORT_ITEN7
	MODULE PROCEDURE EXPORT_STEN7
	MODULE PROCEDURE EXPORT_DTEN7
	MODULE PROCEDURE EXPORT_CTEN7
	MODULE PROCEDURE EXPORT_ZTEN7
! 	MODULE PROCEDURE EXPORT_ITEN8
! 	MODULE PROCEDURE EXPORT_STEN8
! 	MODULE PROCEDURE EXPORT_DTEN8
! 	MODULE PROCEDURE EXPORT_CTEN8
! 	MODULE PROCEDURE EXPORT_ZTEN8
END INTERFACE
INTERFACE IMPORT
	MODULE PROCEDURE IMPORT_ITEN1
	MODULE PROCEDURE IMPORT_DTEN1
	MODULE PROCEDURE IMPORT_ZTEN1
	MODULE PROCEDURE IMPORT_ITEN2
	MODULE PROCEDURE IMPORT_DTEN2
	MODULE PROCEDURE IMPORT_ZTEN2
	MODULE PROCEDURE IMPORT_ITEN3
	MODULE PROCEDURE IMPORT_DTEN3
	MODULE PROCEDURE IMPORT_ZTEN3
	MODULE PROCEDURE IMPORT_ITEN4
	MODULE PROCEDURE IMPORT_DTEN4
	MODULE PROCEDURE IMPORT_ZTEN4
	MODULE PROCEDURE IMPORT_ITEN5
	MODULE PROCEDURE IMPORT_DTEN5
	MODULE PROCEDURE IMPORT_ZTEN5
	MODULE PROCEDURE IMPORT_ITEN6
	MODULE PROCEDURE IMPORT_DTEN6
	MODULE PROCEDURE IMPORT_ZTEN6
	MODULE PROCEDURE IMPORT_ITEN7
	MODULE PROCEDURE IMPORT_DTEN7
	MODULE PROCEDURE IMPORT_ZTEN7
! 	MODULE PROCEDURE IMPORT_ITEN8
! 	MODULE PROCEDURE IMPORT_DTEN8
! 	MODULE PROCEDURE IMPORT_ZTEN8
END INTERFACE
LOGICAL :: MATHIO_MESSAGE = .TRUE.
CHARACTER(*), PARAMETER :: WARN1 = 'Warning: IMPORT::data file inconsistent with target variable.'
CONTAINS

SUBROUTINE EXPORT_ITEN1(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	INTEGER, INTENT(IN)      :: TEN(:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 9, ARRAY_DEPTH = 1
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1,RANK(TEN))]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_ITEN1

SUBROUTINE EXPORT_STEN1(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*4, INTENT(IN)       :: TEN(:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 12, ARRAY_DEPTH = 1
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_STEN1

SUBROUTINE EXPORT_DTEN1(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*8, INTENT(IN)       :: TEN(:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 13, ARRAY_DEPTH = 1
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_DTEN1

SUBROUTINE EXPORT_CTEN1(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*8, INTENT(IN)    :: TEN(:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 4, ARRAY_DEPTH = 1
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_CTEN1

SUBROUTINE EXPORT_ZTEN1(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*16, INTENT(IN)   :: TEN(:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 5, ARRAY_DEPTH = 1
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_ZTEN1

SUBROUTINE EXPORT_ITEN2(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	INTEGER, INTENT(IN)      :: TEN(:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 9, ARRAY_DEPTH = 2
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1,RANK(TEN))]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_ITEN2

SUBROUTINE EXPORT_STEN2(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*4, INTENT(IN)       :: TEN(:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 12, ARRAY_DEPTH = 2
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_STEN2

SUBROUTINE EXPORT_DTEN2(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*8, INTENT(IN)       :: TEN(:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 13, ARRAY_DEPTH = 2
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_DTEN2

SUBROUTINE EXPORT_CTEN2(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*8, INTENT(IN)    :: TEN(:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 4, ARRAY_DEPTH = 2
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_CTEN2

SUBROUTINE EXPORT_ZTEN2(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*16, INTENT(IN)   :: TEN(:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 5, ARRAY_DEPTH = 2
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_ZTEN2

SUBROUTINE EXPORT_ITEN3(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	INTEGER, INTENT(IN)      :: TEN(:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 9, ARRAY_DEPTH = 3
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1,RANK(TEN))]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_ITEN3

SUBROUTINE EXPORT_STEN3(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*4, INTENT(IN)       :: TEN(:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 12, ARRAY_DEPTH = 3
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_STEN3

SUBROUTINE EXPORT_DTEN3(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*8, INTENT(IN)       :: TEN(:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 13, ARRAY_DEPTH = 3
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_DTEN3

SUBROUTINE EXPORT_CTEN3(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*8, INTENT(IN)    :: TEN(:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 4, ARRAY_DEPTH = 3
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_CTEN3

SUBROUTINE EXPORT_ZTEN3(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*16, INTENT(IN)   :: TEN(:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 5, ARRAY_DEPTH = 3
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_ZTEN3

SUBROUTINE EXPORT_ITEN4(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	INTEGER, INTENT(IN)      :: TEN(:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 9, ARRAY_DEPTH = 4
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1,RANK(TEN))]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_ITEN4

SUBROUTINE EXPORT_STEN4(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*4, INTENT(IN)       :: TEN(:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 12, ARRAY_DEPTH = 4
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_STEN4

SUBROUTINE EXPORT_DTEN4(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*8, INTENT(IN)       :: TEN(:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 13, ARRAY_DEPTH = 4
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_DTEN4

SUBROUTINE EXPORT_CTEN4(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*8, INTENT(IN)    :: TEN(:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 4, ARRAY_DEPTH = 4
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_CTEN4

SUBROUTINE EXPORT_ZTEN4(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*16, INTENT(IN)   :: TEN(:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 5, ARRAY_DEPTH = 4
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_ZTEN4

SUBROUTINE EXPORT_ITEN5(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	INTEGER, INTENT(IN)      :: TEN(:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 9, ARRAY_DEPTH = 5
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1,RANK(TEN))]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_ITEN5

SUBROUTINE EXPORT_STEN5(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*4, INTENT(IN)       :: TEN(:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 12, ARRAY_DEPTH = 5
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_STEN5

SUBROUTINE EXPORT_DTEN5(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*8, INTENT(IN)       :: TEN(:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 13, ARRAY_DEPTH = 5
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_DTEN5

SUBROUTINE EXPORT_CTEN5(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*8, INTENT(IN)    :: TEN(:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 4, ARRAY_DEPTH = 5
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_CTEN5

SUBROUTINE EXPORT_ZTEN5(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*16, INTENT(IN)   :: TEN(:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 5, ARRAY_DEPTH = 5
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_ZTEN5

SUBROUTINE EXPORT_ITEN6(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	INTEGER, INTENT(IN)      :: TEN(:,:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 9, ARRAY_DEPTH = 6
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1,RANK(TEN))]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_ITEN6

SUBROUTINE EXPORT_STEN6(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*4, INTENT(IN)       :: TEN(:,:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 12, ARRAY_DEPTH = 6
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_STEN6

SUBROUTINE EXPORT_DTEN6(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*8, INTENT(IN)       :: TEN(:,:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 13, ARRAY_DEPTH = 6
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_DTEN6

SUBROUTINE EXPORT_CTEN6(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*8, INTENT(IN)    :: TEN(:,:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 4, ARRAY_DEPTH = 6
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_CTEN6

SUBROUTINE EXPORT_ZTEN6(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*16, INTENT(IN)   :: TEN(:,:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 5, ARRAY_DEPTH = 6
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_ZTEN6

SUBROUTINE EXPORT_ITEN7(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	INTEGER, INTENT(IN)      :: TEN(:,:,:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 9, ARRAY_DEPTH = 7
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1,RANK(TEN))]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_ITEN7

SUBROUTINE EXPORT_STEN7(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*4, INTENT(IN)       :: TEN(:,:,:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 12, ARRAY_DEPTH = 7
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_STEN7

SUBROUTINE EXPORT_DTEN7(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*8, INTENT(IN)       :: TEN(:,:,:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 13, ARRAY_DEPTH = 7
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_DTEN7

SUBROUTINE EXPORT_CTEN7(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*8, INTENT(IN)    :: TEN(:,:,:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 4, ARRAY_DEPTH = 7
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_CTEN7

SUBROUTINE EXPORT_ZTEN7(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*16, INTENT(IN)   :: TEN(:,:,:,:,:,:,:)
	INTEGER*1, PARAMETER     :: BINARY_TYPE = 5, ARRAY_DEPTH = 7
	INTEGER*1 :: I
	
	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "REPLACE", ACCESS = "stream")
	WRITE(99) BINARY_TYPE
	WRITE(99) ARRAY_DEPTH
	WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
	WRITE(99) TEN
	CLOSE(99)
END SUBROUTINE EXPORT_ZTEN7

! SUBROUTINE EXPORT_ITEN8(FILENAME, TEN)
! 	CHARACTER(*), INTENT(IN) :: FILENAME
! 	INTEGER, INTENT(IN)      :: TEN(:,:,:,:,:,:,:,:)
!     INTEGER*1, PARAMETER     :: BINARY_TYPE = 9
!     INTEGER*1 :: I
! 	
! 	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
!     OPEN (UNIT = 99, FILE = FILENAME//".dat", &
!         STATUS = "REPLACE", ACCESS = "stream")
!     WRITE(99) BINARY_TYPE
!     WRITE(99) ARRAY_DEPTH
!     WRITE(99) [(SIZE(TEN,I), I = 1,RANK(TEN))]
!     WRITE(99) TEN
!     CLOSE(99)
! END SUBROUTINE EXPORT_ITEN8
! 
! SUBROUTINE EXPORT_STEN8(FILENAME, TEN)
! 	CHARACTER(*), INTENT(IN) :: FILENAME
! 	REAL*4, INTENT(IN)       :: TEN(:,:,:,:,:,:,:,:)
!     INTEGER*1, PARAMETER     :: BINARY_TYPE = 12
!     INTEGER*1 :: I
! 	
! 	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
!     OPEN (UNIT = 99, FILE = FILENAME//".dat", &
!         STATUS = "REPLACE", ACCESS = "stream")
!     WRITE(99) BINARY_TYPE
!     WRITE(99) ARRAY_DEPTH
!     WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
!     WRITE(99) TEN
!     CLOSE(99)
! END SUBROUTINE EXPORT_STEN8
! 
! SUBROUTINE EXPORT_DTEN8(FILENAME, TEN)
! 	CHARACTER(*), INTENT(IN) :: FILENAME
! 	REAL*8, INTENT(IN)       :: TEN(:,:,:,:,:,:,:,:)
!     INTEGER*1, PARAMETER     :: BINARY_TYPE = 13
!     INTEGER*1 :: I
! 	
! 	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
!     OPEN (UNIT = 99, FILE = FILENAME//".dat", &
!         STATUS = "REPLACE", ACCESS = "stream")
!     WRITE(99) BINARY_TYPE
!     WRITE(99) ARRAY_DEPTH
!     WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
!     WRITE(99) TEN
!     CLOSE(99)
! END SUBROUTINE EXPORT_DTEN8
! 
! SUBROUTINE EXPORT_CTEN8(FILENAME, TEN)
! 	CHARACTER(*), INTENT(IN) :: FILENAME
! 	COMPLEX*8, INTENT(IN)    :: TEN(:,:,:,:,:,:,:,:)
!     INTEGER*1, PARAMETER     :: BINARY_TYPE = 4
!     INTEGER*1 :: I
! 	
! 	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
!     OPEN (UNIT = 99, FILE = FILENAME//".dat", &
!         STATUS = "REPLACE", ACCESS = "stream")
!     WRITE(99) BINARY_TYPE
!     WRITE(99) ARRAY_DEPTH
!     WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
!     WRITE(99) TEN
!     CLOSE(99)
! END SUBROUTINE EXPORT_CTEN8
! 
! SUBROUTINE EXPORT_ZTEN8(FILENAME, TEN)
! 	CHARACTER(*), INTENT(IN) :: FILENAME
! 	COMPLEX*16, INTENT(IN)   :: TEN(:,:,:,:,:,:,:,:)
!     INTEGER*1, PARAMETER     :: BINARY_TYPE = 5
!     INTEGER*1 :: I
! 	
! 	IF (MATHIO_MESSAGE) PRINT *, ">>", FILENAME, ".dat"
!     OPEN (UNIT = 99, FILE = FILENAME//".dat", &
!         STATUS = "REPLACE", ACCESS = "stream")
!     WRITE(99) BINARY_TYPE
!     WRITE(99) ARRAY_DEPTH
!     WRITE(99) [(SIZE(TEN,I), I = 1, ARRAY_DEPTH)]
!     WRITE(99) TEN
!     CLOSE(99)
! END SUBROUTINE EXPORT_ZTEN8

SUBROUTINE IMPORT_ITEN1(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	INTEGER, INTENT(OUT)     :: TEN(:)
	INTEGER   :: N1
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 9 .AND. ARRAY_DEPTH == 1) THEN
		READ(99) N1
		READ(99) TEN(1:N1)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_ITEN1

SUBROUTINE IMPORT_DTEN1(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*8, INTENT(OUT)      :: TEN(:)
	INTEGER   :: N1
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 13 .AND. ARRAY_DEPTH == 1) THEN
		READ(99) N1
		READ(99) TEN(1:N1)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_DTEN1

SUBROUTINE IMPORT_ZTEN1(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*16, INTENT(OUT)  :: TEN(:)
	INTEGER   :: N1
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 5 .AND. ARRAY_DEPTH == 1) THEN
		READ(99) N1
		READ(99) TEN(1:N1)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_ZTEN1

SUBROUTINE IMPORT_ITEN2(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	INTEGER, INTENT(OUT)     :: TEN(:,:)
	INTEGER   :: N1, N2
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 9 .AND. ARRAY_DEPTH == 2) THEN
		READ(99) N1, N2
		READ(99) TEN(1:N1,1:N2)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_ITEN2

SUBROUTINE IMPORT_DTEN2(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*8, INTENT(OUT)      :: TEN(:,:)
	INTEGER   :: N1, N2
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 13 .AND. ARRAY_DEPTH == 2) THEN
		READ(99) N1, N2
		READ(99) TEN(1:N1,1:N2)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_DTEN2

SUBROUTINE IMPORT_ZTEN2(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*16, INTENT(OUT)  :: TEN(:,:)
	INTEGER   :: N1, N2
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 5 .AND. ARRAY_DEPTH == 2) THEN
		READ(99) N1, N2
		READ(99) TEN(1:N1,1:N2)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_ZTEN2

SUBROUTINE IMPORT_ITEN3(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	INTEGER, INTENT(OUT)     :: TEN(:,:,:)
	INTEGER   :: N1, N2, N3
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 9 .AND. ARRAY_DEPTH == 3) THEN
		READ(99) N1, N2, N3
		READ(99) TEN(1:N1,1:N2,1:N3)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_ITEN3

SUBROUTINE IMPORT_DTEN3(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*8, INTENT(OUT)      :: TEN(:,:,:)
	INTEGER   :: N1, N2, N3
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 13 .AND. ARRAY_DEPTH == 3) THEN
		READ(99) N1, N2, N3
		READ(99) TEN(1:N1,1:N2,1:N3)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_DTEN3

SUBROUTINE IMPORT_ZTEN3(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*16, INTENT(OUT)  :: TEN(:,:,:)
	INTEGER   :: N1, N2, N3
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 5 .AND. ARRAY_DEPTH == 3) THEN
		READ(99) N1, N2, N3
		READ(99) TEN(1:N1,1:N2,1:N3)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_ZTEN3

SUBROUTINE IMPORT_ITEN4(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	INTEGER, INTENT(OUT)     :: TEN(:,:,:,:)
	INTEGER   :: N1, N2, N3, N4
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 9 .AND. ARRAY_DEPTH == 4) THEN
		READ(99) N1, N2, N3, N4
		READ(99) TEN(1:N1,1:N2,1:N3,1:N4)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_ITEN4

SUBROUTINE IMPORT_DTEN4(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*8, INTENT(OUT)      :: TEN(:,:,:,:)
	INTEGER   :: N1, N2, N3, N4
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 13 .AND. ARRAY_DEPTH == 4) THEN
		READ(99) N1, N2, N3, N4
		READ(99) TEN(1:N1,1:N2,1:N3,1:N4)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_DTEN4

SUBROUTINE IMPORT_ZTEN4(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*16, INTENT(OUT)  :: TEN(:,:,:,:)
	INTEGER   :: N1, N2, N3, N4
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 5 .AND. ARRAY_DEPTH == 4) THEN
		READ(99) N1, N2, N3, N4
		READ(99) TEN(1:N1,1:N2,1:N3,1:N4)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_ZTEN4

SUBROUTINE IMPORT_ITEN5(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	INTEGER, INTENT(OUT)     :: TEN(:,:,:,:,:)
	INTEGER   :: N1, N2, N3, N4, N5
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 9 .AND. ARRAY_DEPTH == 5) THEN
		READ(99) N1, N2, N3, N4, N5
		READ(99) TEN(1:N1,1:N2,1:N3,1:N4,1:N5)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_ITEN5

SUBROUTINE IMPORT_DTEN5(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*8, INTENT(OUT)      :: TEN(:,:,:,:,:)
	INTEGER   :: N1, N2, N3, N4, N5
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 13 .AND. ARRAY_DEPTH == 5) THEN
		READ(99) N1, N2, N3, N4, N5
		READ(99) TEN(1:N1,1:N2,1:N3,1:N4,1:N5)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_DTEN5

SUBROUTINE IMPORT_ZTEN5(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*16, INTENT(OUT)  :: TEN(:,:,:,:,:)
	INTEGER   :: N1, N2, N3, N4, N5
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 5 .AND. ARRAY_DEPTH == 5) THEN
		READ(99) N1, N2, N3, N4, N5
		READ(99) TEN(1:N1,1:N2,1:N3,1:N4,1:N5)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_ZTEN5

SUBROUTINE IMPORT_ITEN6(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	INTEGER, INTENT(OUT)     :: TEN(:,:,:,:,:,:)
	INTEGER   :: N1, N2, N3, N4, N5, N6
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 9 .AND. ARRAY_DEPTH == 6) THEN
		READ(99) N1, N2, N3, N4, N5, N6
		READ(99) TEN(1:N1,1:N2,1:N3,1:N4,1:N5,1:N6)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_ITEN6

SUBROUTINE IMPORT_DTEN6(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*8, INTENT(OUT)      :: TEN(:,:,:,:,:,:)
	INTEGER   :: N1, N2, N3, N4, N5, N6
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 13 .AND. ARRAY_DEPTH == 6) THEN
		READ(99) N1, N2, N3, N4, N5, N6
		READ(99) TEN(1:N1,1:N2,1:N3,1:N4,1:N5,1:N6)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_DTEN6

SUBROUTINE IMPORT_ZTEN6(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*16, INTENT(OUT)  :: TEN(:,:,:,:,:,:)
	INTEGER   :: N1, N2, N3, N4, N5, N6
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 5 .AND. ARRAY_DEPTH == 6) THEN
		READ(99) N1, N2, N3, N4, N5, N6
		READ(99) TEN(1:N1,1:N2,1:N3,1:N4,1:N5,1:N6)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_ZTEN6

SUBROUTINE IMPORT_ITEN7(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	INTEGER, INTENT(OUT)     :: TEN(:,:,:,:,:,:,:)
	INTEGER   :: N1, N2, N3, N4, N5, N6, N7
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 9 .AND. ARRAY_DEPTH == 7) THEN
		READ(99) N1, N2, N3, N4, N5, N6, N7
		READ(99) TEN(1:N1,1:N2,1:N3,1:N4,1:N5,1:N6,1:N7)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_ITEN7

SUBROUTINE IMPORT_DTEN7(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	REAL*8, INTENT(OUT)      :: TEN(:,:,:,:,:,:,:)
	INTEGER   :: N1, N2, N3, N4, N5, N6, N7
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 13 .AND. ARRAY_DEPTH == 7) THEN
		READ(99) N1, N2, N3, N4, N5, N6, N7
		READ(99) TEN(1:N1,1:N2,1:N3,1:N4,1:N5,1:N6,1:N7)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_DTEN7

SUBROUTINE IMPORT_ZTEN7(FILENAME, TEN)
	CHARACTER(*), INTENT(IN) :: FILENAME
	COMPLEX*16, INTENT(OUT)  :: TEN(:,:,:,:,:,:,:)
	INTEGER   :: N1, N2, N3, N4, N5, N6, N7
	INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
	
	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
	OPEN (UNIT = 99, FILE = FILENAME//".dat", &
		STATUS = "UNKNOWN", ACCESS = "STREAM")
	READ(99) BINARY_TYPE
	READ(99) ARRAY_DEPTH
	IF (BINARY_TYPE == 5 .AND. ARRAY_DEPTH == 7) THEN
		READ(99) N1, N2, N3, N4, N5, N6, N7
		READ(99) TEN(1:N1,1:N2,1:N3,1:N4,1:N5,1:N6,1:N7)
	ELSE
		IF (MATHIO_MESSAGE) PRINT *, WARN1
	END IF
	CLOSE(99)
END SUBROUTINE IMPORT_ZTEN7

! SUBROUTINE IMPORT_ITEN8(FILENAME, TEN)
!     CHARACTER(*), INTENT(IN) :: FILENAME
!     INTEGER, INTENT(OUT)     :: TEN(:,:,:,:,:,:,:,:)
!     INTEGER   :: N1, N2, N3, N4, N5, N6, N7, N8
!     INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
!     
! 	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
!     OPEN (UNIT = 99, FILE = FILENAME//".dat", &
!         STATUS = "UNKNOWN", ACCESS = "STREAM")
!     READ(99) BINARY_TYPE
!     READ(99) ARRAY_DEPTH
!     IF (BINARY_TYPE == 9 .AND. ARRAY_DEPTH == 8) THEN
!         READ(99) N1, N2, N3, N4, N5, N6, N7, N8
!         READ(99) TEN(1:N1,1:N2,1:N3,1:N4,1:N5,1:N6,1:N7,1:N8)
!     ELSE
!         IF (MATHIO_MESSAGE) PRINT *, WARN1
!     END IF
!     CLOSE(99)
! END SUBROUTINE IMPORT_ITEN8
! 
! SUBROUTINE IMPORT_DTEN8(FILENAME, TEN)
!     CHARACTER(*), INTENT(IN) :: FILENAME
!     REAL*8, INTENT(OUT)      :: TEN(:,:,:,:,:,:,:,:)
!     INTEGER   :: N1, N2, N3, N4, N5, N6, N7, N8
!     INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
!     
! 	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
!     OPEN (UNIT = 99, FILE = FILENAME//".dat", &
!         STATUS = "UNKNOWN", ACCESS = "STREAM")
!     READ(99) BINARY_TYPE
!     READ(99) ARRAY_DEPTH
!     IF (BINARY_TYPE == 13 .AND. ARRAY_DEPTH == 8) THEN
!         READ(99) N1, N2, N3, N4, N5, N6, N7, N8
!         READ(99) TEN(1:N1,1:N2,1:N3,1:N4,1:N5,1:N6,1:N7,1:N8)
!     ELSE
!         IF (MATHIO_MESSAGE) PRINT *, WARN1
!     END IF
!     CLOSE(99)
! END SUBROUTINE IMPORT_DTEN8
! 
! SUBROUTINE IMPORT_ZTEN8(FILENAME, TEN)
!     CHARACTER(*), INTENT(IN) :: FILENAME
!     COMPLEX*16, INTENT(OUT)  :: TEN(:,:,:,:,:,:,:,:)
!     INTEGER   :: N1, N2, N3, N4, N5, N6, N7, N8
!     INTEGER*1 :: BINARY_TYPE, ARRAY_DEPTH
!     
! 	IF (MATHIO_MESSAGE) PRINT *, "<<", FILENAME, ".dat"
!     OPEN (UNIT = 99, FILE = FILENAME//".dat", &
!         STATUS = "UNKNOWN", ACCESS = "STREAM")
!     READ(99) BINARY_TYPE
!     READ(99) ARRAY_DEPTH
!     IF (BINARY_TYPE == 5 .AND. ARRAY_DEPTH == 8) THEN
!         READ(99) N1, N2, N3, N4, N5, N6, N7, N8
!         READ(99) TEN(1:N1,1:N2,1:N3,1:N4,1:N5,1:N6,1:N7,1:N8)
!     ELSE
!         IF (MATHIO_MESSAGE) PRINT *, WARN1
!     END IF
!     CLOSE(99)
! END SUBROUTINE IMPORT_ZTEN8

! end of module MATHIO
END MODULE MATHIO